name: Checking build for Windows

on:
  pull_request:
    paths:
      - "CiCd/WindowsDockerfile"

jobs:
  build-project:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install required tools
      - name: Install dependencies
        run: |
          choco install cmake python3 mingw ninja git --confirm
          refreshenv

      # Configure the project
      - name: Configure project
        run: |
          cmake -S . -B build \
            -DCMAKE_GENERATOR=Ninja \
            -DCMAKE_MAKE_PROGRAM=ninja \
            -DBUILD_ALICE=OFF

      # Build the project
      - name: Build project
        run: cmake --build build
