name: Checking build for Windows

on:
  pull_request:
    paths:
      - "**"
      - "!CiCd/**"

jobs:
  build-project:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install required tools
      - name: Install dependencies
        shell: pwsh
        run: |
          choco install cmake python3 ninja git --confirm
          Invoke-WebRequest -Uri https://github.com/brechtsanders/winlibs_mingw/releases/download/15.1.0posix-12.0.0-ucrt-r1/winlibs-i686-posix-dwarf-gcc-15.1.0-mingw-w64ucrt-12.0.0-r1.zip -OutFile mingw.zip
          Expand-Archive -Path mingw.zip -DestinationPath C:\mingw
          $env:Path += ";C:\mingw\bin"
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"

      # Configure the project
      - name: Configure project
        run: |
          cmake -S . -B build -DCMAKE_C_COMPILER=C:/mingw/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/mingw/bin/g++.exe -G Ninja -DCMAKE_BUILD_TYPE=Release

      # Build the project
      - name: Build project
        run: cmake --build build
